apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-workloads
  namespace: flux-system
spec:
  encryptedData:
    identity: AgCnJswhvJlICu0MZyUeq6ZqT4MfFiq5n87RtdKvZYXYCwvEnCmC5kQ1eP+ewTNiRt6NTk3jlTb6mI23x2/9aijitkSJy5rhV9SGeJRwNNxi+RPADDJgq22XDgGP2mo1UsKhnNvpK3CTD7K3PcezqLgDYHaUzhLWKBi7Wy6Z1X3wsvSoSyAd5ArxcIiYey5FnZAgiMh4xngTYxNJBDAttRp/sSS0sO2BOgxLEnl2JzVMziBQAyjBajg0DZ/Xo4LRJISm99qxaKyXoq5R3NpuB7ntJrrUGXmddVPUEDwNdM3YfbMDtITIVH2yHtLErQsx2xSSKCO93HDyJaiivsxrfRtqjkEvl6OLOSMVY/r/BAsQ6I452V3LITt4F2FRTorZrdRDP4ESxEPxwFpRZtq+i3Rsf0kiaHO29Db/mi66uJuJrfwDqEGjpoVAeinW7UwByELIZPEdWYkZEp/wHpHS+tr1ILIWplS5gzboGk0vxUW0IeLo9pyn7oYUo2pcSZMhd1gPfAtUp0pRt5DH8rQPoeDmait89jw5lClCR+djlRUPB3Pr51I5IDw9LO0EDLOQAPxH8he8DvtVr451Oa+uUEWuC7UnG6nkjUC0yXmDiOForYEyGMd3FjDN5PZ+27+jJEp6LpD3SREhifHm7YXaURF2nR82uJ4mGEYkK+gRNVUdt39ljlV5IvyZNZyFlySmjypwWEBx49Tusq8qirzrI6jXtgpvSXwGaKO8yni3INfF2gZtEJtMVBCH3W8VnwJuiqdu5yUQ3DdN9peV5wNL59b14YT/yiRBBSkRr/l/eR+ePZyZGjNpNBa4XSn+qtkDJH9/vYwSDjncdvhb71RG7xH33cNZOE4qzkH0GNlwKF3rN8RHYo5hx4smrnM6q2x1IZ4+4qtlRZXLgTiyfPvX6Jor7euS72lI7UssJ4gEhNaq4QG4lMEjWzb7AC/lRSBU9spzZwr92bS+AcLYC08q+MIRgx61Of/UvBNcV5MWWxNWZ79qeIPxjSPHsn4vMxRRr4OpjW8uHbUX1h/rZpKOZmfcq4qM0KuOiG2ieggVtFEHVWO0IWmrGO6A0oAoZ7BhXRi9c9e9pCnswd5ntLGoh/f5WAGBJxo58dm83298h5BwvSQ5Q210x/ysScuxG3QeN8mW/ytG3n5cKyIRP2bV6+hy8BxOTP6QGbaK1cn9bQIgD53wAizhr0m2DcXvt02jC3VflcLxUOk0T+ot5d+PLt9D2JyOSaYZySOqRqs=
    identity.pub: AgBggkrPBLVhA+h4eseqj78sqVyXMuNWuQEDl36no1J51WEIrvNc6UpwfJsBkBrSPdiFu6II3RsQy76fSQdYr3SpSkQrV4ccLSlRIuyDCHFFCZYkF2SJpraVJ0z7sIGXVZQuolNnaPTKPhbW1qDveA9HWtvtDEsEbnWUVEGB/RvG0Wkz20qj9ZMwr26BV/b7NnKhJrl4il1Ihkk9gtLebLo9pJixo8PqZo3C1zFDGk7enAl/eSWd9c2CCGEtkzVHqzrRKyD2GmZ7PIodbMN82/heAtmmIYMIM4lRYs7A4gZv2mb6JCx/ANm9vUWHjzvFl8GGEg+aIQm38OaEvpbyblkkwVDeAiChkj2wRGQCi2FVDw+73tmeeIHXnv3LI15V5V1Q3QRiNkbKmQuJvuniX8dfC14XVTJ+aO73bPLVaEtwvakGCZ+ggK5xGZslzzLOQbvB+oYDUMYf8j6ui6KUWjW+9yZdvY6aZTnbLcXTLSQwsMRG+uBxqaTvkpLS6Vd/SbsFDEKx0NTMo/xamGzsiekaLZ8RmkS8CSt1vuXevKWeW/n9R4+IICTQvFnKiXkekirrdbcIJRwHNvnH93Okk3u7c3DQpQBCK3JKbC1KwelTGZs7atCoP1ix8zlxS7tlVdvVctGBX7eJmx3Gpiymek4x7ZdDtR1ibceSxuj2odFoeN//+mYrtMZKL8nbpPBuCWAC1j78iqpzmd1XqBSNlBfwC+S6jxkyb88L8Q6hrXZgp5Cak0ytTA8ZTCk28CKdjkrsknwwdMPm4QWcJa86FbV2zLBmWzio8pvh9Kg/BDimoO0=
    known_hosts: AgAxA2fjgNmwM0VC0PwFKqhq6ou4hRWUTmKoUwxX4AXo/Mey6QWIjHGFpy85+O2/Pvwu/7rB1uZvEvMG9f1IRcXtkIJuWfb+OMYFbQzxOET4BXEeFuRs0odc5WEOZcmJgBsyuAbIlPgeOW0n3LDgAJ2dXOHH8jEggq1614AKRPNMwMs8N/eYNMRfFbV4HOYOdFTk9MJtATQMTMjaRU1YzXQAiNGPXVfWJCYeVDRBmYWYKIZk2ny9QP/dY3jawFou+DbLDUJup612C1PaJEm78QS/9Owxv3M/kNE0/Hai5Jam6hQ9K8AVfxSzrxdjecHnFJwilAOYyAPIuAFlWWRR1SqQ6UIXg6mjTOYx8MXR7vUbJP87c75ikVYPgB14R/d96zyhNk/+w+xABEZ4+saeUnn4yCE1n2TFoV6Hn3CAyA1lVxVG3evenUyOlVGPpMrIjOZOogEcXQzWc93B7EyUlMk6x8tbWOZPLLXNAOkVpb8Jnp+HKAxtsOzlJX1AUaa5ofFktcYcB73nPc86vlM7d5Ziu6/vMLfYMr85UfonGtUHXvKRAqav4GWxx0wXlXVvgMrOJdFo4eufwSuPldyETE5Esq8swjo8fg6Z993xmaBhxr4dz4m9gx+0eYlJ/l6yLfPcsIeJryMI9vDwSZqn9M4qH1G8AK7Ox+91a+G/nBhp3/J7dVwwsfumGFRjWAoUZpmy6bGaiwkBH70HjLBZ11gUrIfdjnVb4mCAy6nFW0tk8aIf6rCHX4ApwtTUMh13PqD6xp5qxyC+7SoyGJBrCXNzWF5o2PQwW3ccq3RbNbIbbvl463OdwOvTvqxLDzs1qffFf+/mnvsaUzAZZRAH4bvPOswlRVCkEp2hH/VCdQ750y2rN63JnRh7PUEeoOU7E7A4XLht0csdmixLTRU3sS3r0OQN9rLZacEvMiw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitops-workloads
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-workloads
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitops-workloads
  timeout: 60s
  url: ssh://git@github.com/iamahgoub/gitops-workloads

