apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  releaseName: karpenter
  targetNamespace: kube-system
  interval: 5m
  chart:
    spec:
      chart: karpenter
      version: '0.36.1'
      sourceRef:
        kind: HelmRepository
        name: karpenter-repository
        namespace: flux-system
      interval: 1m
  values:
    logLevel: debug
    settings:
      clusterName: ${CLUSTER_NAME}
    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
    serviceAccount:
      create: false
      name: karpenter-sa