apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-name
  namespace: flux-system
spec:
  encryptedData:
    identity: AgCH62iF/WbujuRNUjyK6ArSgXdEI6wkkp8wD60duNFSnR5KwEN4Jw8KMRdcJduTBaPbVJD03DMhUkc0pW/qEaZ48cbP+GPlcV5R4EMslG0o2zU1lCIvtHKOvDXOuBg0r3uFPviIYg/3qgNKkixiG1MmxxreDSebM/nuZhH6rSFjrqJTn9ll+cU4qhsLar0KMQNO1xt4yTtjuUoJPfE7arDomu7E6oJkf8DJr15VDTl6VzppPITQ9ruUKHLafKSfaPvblE6+OyNsugyecaAeBBwK158v7s1rcfTRMI/kyuxfAgxSA+tf4flZtrfXkPDsG/fYdvH3HcDCm4HMC5zgiiuXyU/kZIcByHecsdzaIp4YtBB1eJdUWYj3Jwnlc8ZG5rVcyPdkzR6c8bHAWmGGVOfdSKfxrQYB14mUKI9cD/UWiZR5k+/4fxqG3LkYvaHEt2InJxHeK/9KfH3AYAjnsdXYyymWOkye22nP9z454ooD5PkQrzWBM4tqUqiOMe97/SMnJuCMcxWz2KbSIzVJsNgVggX3zHCaTrWdLVPHLjoiwJwN+n8Nkv9+utgZ68r5njjGKsqnYQpow974ya4pGxkNIJUCgDTpMDvmbBYwCwaQ49Aedzsc43CXDYv7YKHwuMEqsXei+UmN5R6uEpi5ofWcA7UHpUaNawd7z2ENERHPGmievWUSkgaHDPuVzgMgcsZWDcA7GeFoLMNbqIfSO+ektj0uoJbb28trS0NHzRNeqqlAIXCTzo+5vVrpf9Kvi4irZjoF92LZQRYBGvmhIyiwplgUAI8ppcvegD77u+U6K/ZjDvzIVWnBMWRyrg35pXDgwiDC1eWtLCECjcE6ZD2VwwigPwyMRhHgmhXWjb7WinH3jP4ETUIj6mV4EUHSgPJTSktxowIvllfVAltSooLB9pxSP8gK/Ss2KvZPosTaZFOqsayboXvEgCd5chRpR/vhvYppUCDiZl8Rfm70GBjIpkc8OjG/HG45q3BkySJ53S9vmrtGMAJpe09ysP0xmGu0iV+y2/HVfqwZqPaE6dyBJpqrkWIZ0SrB714gyFmeXGvjY7QK5eyodiPJ9AvlqBUQjONdHKsP6WuOFB3PwLeIAl0ZpfES/aIo7wAEpxwUXmXeyiAMLzg7zp8oE6Rb3h+QCO6pBOrIfhf9X8jw2Mu63Nk5J6iDvPTGZeygLpq4Onjlui4l3Hi8VCcPV9FG3ZkrDBooa0701jw/n3S2sqTb/b8ps1BKvJmJwN0=
    identity.pub: AgA8WHwD+5aueS74+a+wo37mb/YkMvhFWq39yVQs2nBBKkCkGdw5elhRsm5U0OZGkDAvm0dHfZ3u2V8MImfPhBfpsD4fz5CH43rPr9Rf/YqlVs/FHf9UDjDXZUI9DnLLBNexTD5ckZh+iW7MWZQ9b0HpapVa3+o4PEmJ2Trke3KhdGW9eOwJDZ3HZxTCzeYBxQEx4huxVjTdZEQpheLhbNX46lYRDp1tCcwhiV2wbnJ5ogDCoZL3monPF3WIdnQe5RhEBKMOSOEON7ZoEyLEOWrRApCAhMDaWItOkCSEWZfP2H8X1/KXD9YGiAPN8BtSq3oDMDGp5HABn9mM6DA0r1TP5Vd2CDcJsmirUlksAi0RTjJWld5B9ihBacJ8U4gbaRYwpaNjxlcNHPWrmRsTnAmyOcpd5ZkGuRv34eRkNoA4CtjJOuorgdWZOElexG7SBgoOrQYt1STdACRrWwu8Xv2Ij7w1wv0Uw8YYA2xchrE2/DVRqyOAa9rku2Itg7jfmrMBcwU81MUCmedW+EcXbW4RHVm4BMMHgDRds4leUyG5i/UipEeW0VAsLgyLTae/Uk1tX8+HZcbkPGMVhvjrEVGPCWpwpAH4YWlOi7b2NUPPnaFlgIWmWXfNmklvrU6RozF2XWfM95+hJ1VP8+4PosIdn7S6xv87NFc58vOCIJEJRXg/5q4vIawI6m4mBfjF+1IP7r87SS24UO9f/STD8W08KHtKWpsNf1/2kZIXH/1e0Lo3bijHmGVRjsBBI8tSq9TL45OGnAcLVIdyGz/D6viaOmQbAIyKZRcP9jOT1Gkay50=
    known_hosts: AgDAZPRz7UbZSBWkHEdRryL2+L9pv53EajTL7TZ6u3kIotKKqMJDnSs+ntAr87nTqNOiOYWF5NjxKYRt3WLYTwkia4vszKIPo8fHJd+3Nefe/Q2SwcGDzuW1vG5/pqwjEoykhN+pwBh3zjX4F04A+RQggpiEjZZMynjGwkQt7nD9aE6sC0S7H7l74K86k5ALYYa7Qdx4rtH0KgTKK0Xuq1j9dPDh14IR+0VIgk0M5uHBBrwPjM0sOogp512ECyo5+aXp6zdC5s+EZhrjcyZm81N3sG8vCvAydOs1OO08BezGrJyFqhYAGVWtCQFt3zJypQGYGCSJE+VYPXs7oMByhGpBj9pKzfPJn85mX+ILk7yQPpVaw7BejRECqKWI0P+ZpR6qswGFcsWfDvovkF0rPg6UwTw4MkNUPPlZn/KA1lr2YFzmUjkQOkjQCq0Rezg9tAAawXRZnhaAbhV4aylSSEEqYBtw/5QHcfJXXdHL01x1AXj30mN/YP23rmcad6KOs9fBthlENcS6Y81VtRn13hHxfj3p1DBaTxYbgeOdZM8SmxZZJKL2DuOexIwyDu21v9n79o1aJ7mPuGq4H3ogDig4DQkdM/GGPB2c2GSJXDjdoLcwOl4iDJnfV4G3Q4UdTrgLcPpTSbEYtI4wn8OiVQIisIjRBYjDYOA9IAAg68h28LWN/NCDcKiFmXItABxrfLGNMx06EqeDnQniRI45tosGr2+4jTKCUyaDLiCYVHr3XfABssMAPuEdvqv7X67z683zi8w4Qn6nIoMuuSdkSZvv9cNNQVk9Umny0w2uQfjpxWZnlmsXq/YymjFzi6PkD7JEYcwzDLXD9TRf0zxCOUn9t1zA9S4LkPeSk3RFUEoSX2RfbSNH1k0qNCpgF96kHS+5ETlpn/KFKFEZ90swvr1uo4wBIdPfcXtXBos=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: app-name
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app-name
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: red
  timeout: 60s
  url: ssh://git@github.com/iamahgoub/app-name-manifests

