apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: products
spec:
  forProvider:
    region: AWS_REGION
    attributeDefinitions:
      - attributeName: id
        attributeType: S
    keySchema:
      - attributeName: id
        keyType: HASH
    billingMode: PROVISIONED
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
  providerConfigRef:
    name: default
