---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: OpenIDConnectProvider
metadata:
  name: cluster-oidc-idp-cluster-name
spec:
  forProvider:
    clientIDList:
      - sts.amazonaws.com
    thumbprintList:
      - "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
    url: "https://${OIDC_PROVIDER}"
