apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-name-crossplane-iam
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-name-eks-cluster-oidc-idp
  interval: 1m0s
  path: ./clusters-config/cluster-name/crossplane-iam
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Role
    apiVersion: iam.aws.crossplane.io/v1beta1
    name: crossplane-role-cluster-name
  - kind: RolePolicyAttachment
    apiVersion: iam.aws.crossplane.io/v1beta1
    name: crossplane-rolepolicyattachment-cluster-name
  validation: client
  timeout: 2m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info-cluster-name
        optional: false