---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-name-eks-cluster
  namespace: flux-system
spec:
  interval: 30s
  path: ./clusters-config/cluster-name/def
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Secret
    apiVersion: v1
    name: cluster-name-eks-connection
    namespace: flux-system
  validation: client
  timeout: 2m
