---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-name-external-secrets-config
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-name-external-secrets
  interval: 30s
  path: ./tools-config/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Secret
    apiVersion: v1
    name: sealed-secrets
    namespace: sealed-secrets
  kubeConfig:
    secretRef:
      name: cluster-name-eks-connection
  validation: client
  timeout: 2m
---