---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-load-balancer-controller-iam
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./tools-config/aws-load-balancer-controller-iam
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
  - kind: ServiceAccount
    apiVersion: v1
    name: aws-load-balancer-controller
    namespace: kube-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
---