---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubecost-repository
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://public.ecr.aws/kubecost