apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgANceCsvUl4vZRVQlgaHFSBUZD2maxYbcZFatBJbfFus9riQfBdJdRA2+vvC/Tu9TN2eZygKb7vXe+TMSO85mDVCpKLIe2QlIIEexrWrisFKKkSgLMnNkaYfC4c6kLyGWjg9ZUYYsPacyIZHtQw8vhIfRjQ0mHB4i2+XJfObcNOzT+G4mIcKp/O+czmPNajfeTlA7z8dK7uANGBgAXrd6D4MijbB2dVkI/VAbcXtQkCnvU4ufZMxiDvXlrvH1biWjT+NtmmkR740iB+0YUcTZ2VxMob75DwffIk7WMAIdaH75foUxjx/tT+y/os/DYHZ1XvyairqJGdKnuhLUcpT7w7wV+8hYOxmEoHVrZ90EsDIhEI7a5TxsYpZDAz2T5jf18AnugmloU3pkieDim5ll4uLUmhfKeeCaOPyzrHRMO4u9NUZK8bifEQ1FmDfNBRbzuIhPMWLArfKeZc4mFIW0bplPSqeBFdHK2NCm7mNGQPSgRkjB5zElgwljlBrHOSdWR8CDgEBeIxsIxq0suwRqGzG/ddP87bmWsqbMDQrC0acm56hcW1CSQU3yORikEuAk6PUh+CRVOKY5pvHZ0885kPTAbvM5jHjcJDH1tUidPWdUU2TnZxUCMOzakMib1lw3ac33H2Nr+pIxU5oItMHFSP2baXZjR8EG2ZM2d2KMkLbOMgJjXwjDjKhZvv/CnCbNjhPv3m5+I2Qzb7k/oWy+cGmkENPxtOtRjDu1DO+WecPRGFIved06bChoKGGLyTj7YfOQUh+d4W0ZukvEHZsuSuJd+h26G7OqbvV2M56sDFVSbetvczdwSeLJSSks27Y+mi/70hgftk5HbHatKdECStmJti9g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system
    type: Opaque

