apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-fe
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: product-catalog-fe
        image: public.ecr.aws/h2c3y9h0/multi-cluster-gitops/product-catalog-fe:latest
        env:
        - name: BASE_URL
          value: "http://product-catalog-api-prod.product-catalog-api/products/"
