---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: commercial-prod-external-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: commercial-prod-intialization
  interval: 1m0s
  path: ./clusters-config/commercial-prod/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  timeout: 2m
---