---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: commercial-prod-sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: commercial-prod-external-secrets-config
  interval: 30s
  path: ./clusters-config/commercial-prod/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Deployment
    name: sealed-secrets
    namespace: sealed-secrets
  validation: client
  timeout: 2m
---