---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-ebs-csi
  namespace: flux-system
spec:
  prune: true
  interval: 10m0s
  path: ./tools/aws-ebs-csi
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: aws-ebs-csi-iam
---