---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane
  namespace: flux-system
spec:
  prune: true
  interval: 3m0s
  path: ./tools/crossplane
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  patches:
    - target:
        group: pkg.crossplane.io
        kind: ControllerConfig
        version: v1alpha1
        name: aws-config
      patch: |-
        - op: replace
          path: /metadata/annotations
          value:
            eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/crossplane-role-cluster-name
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
---