---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: karpenter-iam
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./tools-config/karpenter-iam
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: ServiceAccount
    apiVersion: v1
    name: karpenter-sa
    namespace: kube-system
  patches:
    - target:
        group: iam.aws.crossplane.io
        kind: Role
        version: v1beta1
        name: karpenter-role
      patch: |-
        - op: replace
          path: /metadata/name
          value: karpenter-role-cluster-name
    - target:
        group: iam.aws.crossplane.io
        kind: RolePolicyAttachment
        version: v1beta1
        name: karpenter-attachment
      patch: |-
        - op: replace
          path: /metadata/name
          value: karpenter-attachment-cluster-name
        - op: replace
          path: /spec/forProvider/policyArnRef/name
          value: karpenter-policy-cluster-name
        - op: replace
          path: /spec/forProvider/roleNameRef/name
          value: karpenter-role-cluster-name
    - target:
        group: iam.aws.crossplane.io
        kind: Policy
        version: v1beta1
        name: karpenter-policy
      patch: |-
        - op: replace
          path: /metadata/name
          value: karpenter-policy-cluster-name
        - op: replace
          path: /spec/forProvider/name
          value: karpenter-policy-cluster-name
    - target:
        group: ""
        kind: ServiceAccount
        version: v1
        name: karpenter-sa
        namespace: kube-system
      patch: |-
        - op: replace
          path: /metadata/annotations
          value:
            eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/karpenter-role-cluster-name
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
---