---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubecost
  namespace: flux-system
spec:
  prune: true
  interval: 10m0s
  path: ./tools/kubecost
  sourceRef:
    kind: GitRepository
    name: flux-system
---