apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi
  namespace: flux-system
spec:
  releaseName: aws-ebs-csi-driver
  targetNamespace: kube-system
  interval: 5m
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: '2.30.0'
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-repository
        namespace: flux-system
      interval: 1m
  values:
    controller:
      serviceAccount:
        create: false
        name: ebs-csi-controller-sa