apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-fe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: product-catalog-fe
    spec:
      containers:
      - image: public.ecr.aws/h2c3y9h0/multi-cluster-gitops/product-catalog-fe:latest
        env:
        - name: BASE_URL
          value: "http://product-catalog-api.product-catalog-api/products/"
        name: product-catalog-fe
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
