apiVersion: v1
kind: Service
metadata:
  name: product-catalog-fe
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: product-catalog-fe
  type: LoadBalancer
