apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: product-catalog-api
        env:
        - name: PRODUCTS_TABLE_NAME
          value: products-staging