apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-fe
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: product-catalog-fe
        env:
        - name: BASE_URL
          value: "http://product-catalog-api-prod.product-catalog-api/products/"
