---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: crossplane-role
spec:
  forProvider:
    assumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "arn:aws:iam::${ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "${OIDC_PROVIDER}:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                  "${OIDC_PROVIDER}:sub": "system:serviceaccount:crossplane-system:provider-aws-*"
                }
              }
            }
          ]
        }
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: crossplane-rolepolicyattachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AdministratorAccess
    roleNameRef:
      name: crossplane-role
  providerConfigRef:
    name: default