apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: ebs-csi-controller-role
  namespace: kube-system
spec:
  forProvider:
    assumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "arn:aws:iam::${ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "${OIDC_PROVIDER}:aud": "sts.amazonaws.com",
                  "${OIDC_PROVIDER}:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
                }
              }
            }
          ]
        }
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: ebs-csi-controller-attachment
  namespace: kube-system
spec:
  forProvider:
    policyArn: "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
    roleNameRef:
      name: ebs-csi-controller-role