apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: product-catalog-api
    spec:
      serviceAccountName: product-catalog-api-sa
      containers:
      - env:
        - name: PRODUCTS_TABLE_NAME
          value: products
        image: public.ecr.aws/h2c3y9h0/multi-cluster-gitops/product-catalog-api:v1
        name: product-catalog-api
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /products/ping
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /products/ping
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
