apiVersion: v1
kind: Service
metadata:
  name: product-catalog-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: product-catalog-api
  type: LoadBalancer
