---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mgmt
  region: AWS_REGION
  version: "1.29"

iam:
  withOIDC: true

vpc:
  nat:
    gateway: Single

managedNodeGroups:
- name: nodegroup
  privateNetworking: true
  iam:
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  desiredCapacity: 3
  instanceType: t3.small
