---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mgmt
  region: eu-west-1
  version: "1.21"

managedNodeGroups:
- name: nodegroup
  iam:
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - 'secretsmanager:GetResourcePolicy'
        - 'secretsmanager:GetSecretValue'
        - 'secretsmanager:DescribeSecret'
        - 'secretsmanager:ListSecretVersionIds'
        Resource: 'arn:aws:secretsmanager:*:*:secret:sealed-secrets*'
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true
