---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mgmt
  region: AWS_REGION
  version: "1.22"

iam:
  withOIDC: true

managedNodeGroups:
- name: nodegroup
  iam:
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true
