---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clusters-config
  namespace: flux-system
spec:
  prune: true
  dependsOn:
  - name: crossplane-eks-composition
  interval: 2m0s
  path: ./clusters-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---