---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  dependsOn:
  - name: external-secrets
  interval: 3m0s
  path: ./tools-config/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Secret
    apiVersion: v1
    name: sealed-secrets
    namespace: sealed-secrets
  validation: client
  timeout: 2m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
---