---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./tools/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Deployment
    name: external-secrets
    namespace: external-secrets
  validation: client
  timeout: 2m
---