---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: karpenter-config
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./tools-config/karpenter-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
  dependsOn:
  - name: karpenter
  patches:
  - target:
      group: karpenter.k8s.aws
      kind: EC2NodeClass
      name: default
    patch: |-
      apiVersion: karpenter.k8s.aws/v1beta1
      kind: EC2NodeClass
      metadata:
        name: not-used
      spec:
        subnetSelectorTerms:
          - tags:
              Name: "mgmtPrivate*"
---