---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: karpenter-iam
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./tools-config/karpenter-iam
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: ServiceAccount
    apiVersion: v1
    name: karpenter-sa
    namespace: kube-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
---