apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./flux-system
- clusters-config.yaml
- crossplane-eks-composition.yaml
- crossplane.yaml
- karpenter-config.yaml
- karpenter-iam.yaml
- karpenter.yaml

