---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: external-secrets-config
  interval: 3m0s
  path: ./tools/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Deployment
    name: sealed-secrets
    namespace: sealed-secrets
  validation: client
  timeout: 2m
---