apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: product-catalog-api-team-infra-admin
  namespace: flux-system
rules:
- apiGroups:
  - aws.crossplane.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete